name: Monorepo CI
on: [pull_request]
jobs:
  validate-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/validate-domain-layout.sh
      - run: bash scripts/validate-best-practices.sh
